export enum EnumErrorFunc {
  UNKNOWN="UNKNOWN",
  CREATE_USER="CREATE_USER",
  SAVE_USER="SAVE_USER",
  DELETE_USER="DELETE_USER",
  LOAD_USER="LOAD_USER",
  MODIFY_SECRET="MODIFY_SECRET",
  MODIFIY_ADMIN = "MODIFIY_ADMIN",
  MODIFY_VALIDEUR = "MODIFY_VALIDEUR",
  LOAD_VACATION = "LOAD_VACATION",
  SAVE_VACATION = "SAVE_VACATION",
}

export enum EnumErrorMessage {
  UNKNOWN= "UNKNOWN",
  NO_LOGIN_PWD_FOUND = "NO_LOGIN_PWD_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  MISSING_ARG = "MISSING_ARG",
  ERROR_CREATEUSER = "ERROR_CREATEUSER",
  MISSING_OR_WRONG_DATE = "MISSING_OR_WRONG_DATE"
}

export class TVError {
  type: EnumErrorMessage;
  func: EnumErrorFunc
}
